### ISSUE TITLE
How to test the pre-trained TDy_VGG model

### ISSUE THREAD

**Issue by Ian-Tam** [shkim816/temporal_dynamic_cnn#4]
Hello,
Thanks for your excellent work, I would like to know how to test the pre-trained TDy_VGG model. When I was testing, the results were bad, I think it might be a problem with the parameters.

**Comment by shkim816** [comment]
We checked that there were no problems in the pre-trained TDy_VGG model and code.
I think that the pre-trained model is not loaded during evaluation.

Please run the following script and you can show that 'Model pretrained_TDy_VGG.model loaded!'.

python trainSpeakerNet.py --eval --model TDy_VGGVox --initial_model pretrained_TDy_VGG.model
